services:
  nodepad:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodepad
    restart: unless-stopped
    environment:
      NODEPAD_AUTH_PASSWORD: 
    ports:
      - "3000:3000"
